import React from 'react'
import styled from 'styled-components'

const PrivacyPolicy = () => {
  return (
    <>
      <MainContainer>
        <SubContainer>
          <Title>PRIVACY POLICY</Title>
          <FirstSection>
            <p>Effective date: 04/01/2022</p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>1. Introduction</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              Welcome to<b> WeFleet Pty Ltd.</b>
            </p>
            <p>&nbsp;</p>
            <p>
              WeFleet Pty Ltd&nbsp;(&ldquo;us&rdquo;, &ldquo;we&rdquo;, or
              &ldquo;our&rdquo;) operates&nbsp;https://wefleet.co and WeFleet Driver App
              mobile application&nbsp;(hereinafter referred to as <b>"Service"</b>).
            </p>
            <p>&nbsp;</p>
            <p>
              Our Privacy Policy governs your visit to https://wefleet.co and WeFleet
              Driver App mobile application, and explains how we collect, safeguard and
              disclose information that results from your use of our Service.&nbsp;
            </p>
            <p>&nbsp;</p>
            <p>
              We use your data to provide and improve Service. By using Service, you agree
              to the collection and use of information in accordance with this policy.
              Unless otherwise defined in this Privacy Policy, the terms used in this
              Privacy Policy have the same meanings as in our Terms and Conditions.
            </p>
            <p>&nbsp;</p>
            <p>
              Our Terms and Conditions (<b>"Terms"</b>) govern all use of our Service and
              together with the Privacy Policy constitutes your agreement with us (
              <b>"agreement"</b>).
            </p>
            <br></br>
            <p>
              <b>
                <u>2. Definitions</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              <b>SERVICE</b> means the&nbsp;https://wefleet.co website and WeFleet Driver
              App mobile application&nbsp;operated by&nbsp;WeFleet Pty Ltd.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>PERSONAL DATA</b> means data about a living individual who can be
              identified from those data (or from those and other information either in
              our possession or likely to come into our possession).
            </p>
            <p>&nbsp;</p>
            <p>
              <b>USAGE DATA</b> is data collected automatically either generated by the
              use of Service or from Service infrastructure itself (for example, the
              duration of a page visit).
            </p>
            <p>&nbsp;</p>
            <p>
              <b>COOKIES</b> are small files stored on your device (computer or mobile
              device).
            </p>
            <p>&nbsp;</p>
            <p>
              <b>DATA CONTROLLER</b> means a natural or legal person who (either alone or
              jointly or in common with other persons) determines the purposes for which
              and the manner in which any personal data are, or are to be, processed. For
              the purpose of this Privacy Policy, we are a Data Controller of your data.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal
              person who processes the data on behalf of the Data Controller. We may use
              the services of various Service Providers in order to process your data more
              effectively.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>DATA SUBJECT</b> is any living individual who is the subject of Personal
              Data.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>THE USER</b> is the individual using our Service. The User corresponds to
              the Data Subject, who is the subject of Personal Data.
            </p>
            <br></br>
            <p>
              <b>
                <u>3. Information Collection and Use</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We collect several different types of information for various purposes to
              provide and improve our Service to you.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>4. Types of Data Collected</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Personal Data</b>
            </p>
            <p>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or identify
              you (<b>"Personal Data"</b>). Personally identifiable information may
              include, but is not limited to:
            </p>
            <p>&nbsp;</p>
            <ol type="a">
              <li>
                <p>Email address</p>
              </li>
              <br></br>
              <li>
                <p>First name and last name</p>
              </li>
              <br></br>
              <li>
                <p>Phone number</p>
              </li>
              <br></br>
              <li>
                <p>Address, State, Province, ZIP/Postal code, City</p>
              </li>
              <br></br>
              <li>
                <p>Cookies and Usage Data</p>
              </li>
            </ol>
            <p>&nbsp;</p>
            <p>
              We may use your Personal Data to contact you with newsletters, marketing or
              promotional materials and other information that may be of interest to you.
              You may opt out of receiving any, or all, of these communications from
              us&nbsp;by emailing at&nbsp;integrations@wefleet.co.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Usage Data</b>
            </p>
            <p>
              We may also collect information that your browser sends whenever you visit
              our Service or when you access Service by or through a mobile device (
              <b>"Usage Data"</b>).
            </p>
            <p>&nbsp;</p>
            <p>
              This Usage Data may include information such as your computer&apos;s
              Internet Protocol address (e.g. IP address), browser type, browser version,
              the pages of our Service that you visit, the time and date of your visit,
              the time spent on those pages, unique device identifiers and other
              diagnostic data.
            </p>
            <p>&nbsp;</p>
            <p>
              When you access Service with a mobile device, this Usage Data may include
              information such as the type of mobile device you use, your mobile device
              unique ID, the IP address of your mobile device, your mobile operating
              system, the type of mobile Internet browser you use, unique device
              identifiers and other diagnostic data.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Location Data</b>
            </p>
            <p>
              We may use and store information about your location if you give us
              permission to do so (<b>"Location Data"</b>). We use this data to provide
              features of our Service, to improve and customize our Service. We also use
              this data to be able to get different items such as Delivery ETA&rsquo;s and
              more to provide a better service.
            </p>
            <p>&nbsp;</p>
            <p>
              You can enable or disable location services when you use our Service at any
              time by way of your device settings.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Tracking Cookies Data</b>
            </p>
            <p>
              We use cookies and similar tracking technologies to track the activity on
              our Service and we hold certain information.
            </p>
            <p>&nbsp;</p>
            <p>
              Cookies are files with a small amount of data which may include an anonymous
              unique identifier. Cookies are sent to your browser from a website and
              stored on your device. Other tracking technologies are also used such as
              beacons, tags and scripts to collect and track information and to improve
              and analyze our Service.
            </p>
            <p>&nbsp;</p>
            <p>
              You can instruct your browser to refuse all cookies or to indicate when a
              cookie is being sent. However, if you do not accept cookies, you may not be
              able to use some portions of our Service.
            </p>
            <p>&nbsp;</p>
            <p>Examples of Cookies we use:</p>
            <p>&nbsp;</p>
            <ol type="a">
              <li>
                <p>
                  <b>Session Cookies:</b> We use Session Cookies to operate our Service.
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  <b>Preference Cookies:</b> We use Preference Cookies to remember your
                  preferences and various settings.
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  <b>Security Cookies:</b> We use Security Cookies for security purposes.
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  <b>Advertising Cookies:</b> Advertising Cookies are used to serve you
                  with advertisements that may be relevant to you and your interests.
                </p>
              </li>
            </ol>
            <br></br>
            <p>
              <b>
                <u>5. Use of Data</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>WeFleet Pty Ltd&nbsp;uses the collected data for various purposes:</p>
            <p>&nbsp;</p>
            <ol type="a">
              <li>
                <p>to provide and maintain our Service;</p>
              </li>
              <br></br>
              <li>
                <p>to notify you about changes to our Service;&nbsp;</p>
              </li>
              <br></br>
              <li>
                <p>
                  to allow you to participate in interactive features of our Service when
                  you choose to do so;&nbsp;
                </p>
              </li>
              <br></br>
              <li>
                <p>to provide customer support;&nbsp;</p>
              </li>
              <br></br>
              <li>
                <p>
                  to gather analysis or valuable information so that we can improve our
                  Service;&nbsp;
                </p>
              </li>
              <br></br>
              <li>
                <p>to monitor the usage of our Service;</p>
              </li>
              <br></br>
              <li>
                <p>to detect, prevent and address technical issues;</p>
              </li>
              <br></br>
              <li>
                <p>to fulfill any other purpose for which you provide it;</p>
              </li>
              <br></br>
              <li>
                <p>
                  to carry out our obligations and enforce our rights arising from any
                  contracts entered into between you and us, including for billing and
                  collection;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  to provide you with notices about your account and/or subscription,
                  including expiration and renewal notices, email-instructions, etc.;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  to provide you with news, special offers and general information about
                  other goods, services and events which we offer that are similar to
                  those that you have already purchased or enquired about unless you have
                  opted not to receive such information;
                </p>
              </li>
              <br></br>
              <li>
                <p>in any other way we may describe when you provide the information;</p>
              </li>
              <br></br>
              <li>
                <p>for any other purpose with your consent.&nbsp;</p>
              </li>
            </ol>
            <br></br>
            <p>
              <b>
                <u>6. Retention of Data</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We will retain your Personal Data only for as long as is necessary for the
              purposes set out in this Privacy Policy. We will retain and use your
              Personal Data to the extent necessary to comply with our legal obligations
              (for example, if we are required to retain your data to comply with
              applicable laws), resolve disputes, and enforce our legal agreements and
              policies.
            </p>
            <p>&nbsp;</p>
            <p>
              We will also retain Usage Data for internal analysis purposes. Usage Data is
              generally retained for a shorter period, except when this data is used to
              strengthen the security or to improve the functionality of our Service, or
              we are legally obligated to retain this data for longer time periods.
            </p>
            <br></br>
            <p>
              <b>
                <u>7. Transfer of Data</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              Your information, including Personal Data, may be transferred to – and
              maintained on – computers located outside of your state, province, country
              or other governmental jurisdiction where the data protection laws may differ
              from those of your jurisdiction.
            </p>
            <p>&nbsp;</p>
            <p>
              Your consent to this Privacy Policy followed by your submission of such
              information represents your agreement to that transfer.
            </p>
            <p>&nbsp;</p>
            <p>
              WeFleet Pty Ltd will take all the steps reasonably necessary to ensure that
              your data is treated securely and in accordance with this Privacy Policy and
              no transfer of your Personal Data will take place to an organisation or a
              country unless there are adequate controls in place including the security
              of your data and other personal information.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>8. Disclosure of Data</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>We may disclose personal information that we collect, or you provide:</p>
            <p>&nbsp;</p>
            <ol type="a">
              <li>
                <p>
                  <b>Disclosure for Law Enforcement.</b>
                </p>
                <br></br>
                <p>
                  Under certain circumstances, we may be required to disclose your
                  Personal Data if required to do so by law or in response to valid
                  requests by public authorities.
                </p>
              </li>
              <p>&nbsp;</p>
              <li>
                <p>
                  <b>Other cases. We may disclose your information also:</b>
                </p>
                <br></br>
                <ol type="i">
                  <li>
                    <p>to our subsidiaries and affiliates;</p>
                  </li>
                  <br></br>
                  <li>
                    <p>
                      to contractors, service providers, and other third parties we use to
                      support our business;
                    </p>
                  </li>
                  <br></br>
                  <li>
                    <p>to fulfill the purpose for which you provide it;</p>
                  </li>
                </ol>
              </li>
            </ol>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>9. Security of Data</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              The security of your data is important to us but remember that no method of
              transmission over the Internet or method of electronic storage is 100%
              secure. While we strive to use commercially acceptable means to protect your
              Personal Data, we cannot guarantee its absolute security.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>
                  10. Your Data Protection Rights Under General Data Protection Regulation
                  (GDPR)
                </u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We aim to take reasonable steps to allow you to correct, amend, delete, or
              limit the use of your Personal Data.
            </p>
            <p>&nbsp;</p>
            <p>
              If you wish to be informed what Personal Data we hold about you and if you
              want it to be removed from our systems, please email us at info@wefleet.co.
            </p>
            <p>&nbsp;</p>
            <p>
              In certain circumstances, you have the following data protection rights:
            </p>
            <br></br>
            <ol type="a">
              <li>
                <p>
                  the right to access, update or to delete the information we have on you;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  the right of rectification. You have the right to have your information
                  rectified if that information is inaccurate or incomplete;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  the right to object. You have the right to object to our processing of
                  your Personal Data;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  the right of restriction. You have the right to request that we restrict
                  the processing of your personal information;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  the right to data portability. You have the right to be provided with a
                  copy of your Personal Data in a structured, machine-readable and
                  commonly used format;
                </p>
              </li>
              <br></br>
              <li>
                <p>
                  the right to withdraw consent. You also have the right to withdraw your
                  consent at any time where we rely on your consent to process your
                  personal information;
                </p>
              </li>
            </ol>
            <br></br>
            <p>
              Please note that we may ask you to verify your identity before responding to
              such requests. Please note, we may not able to provide Service without some
              necessary data.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>11. Service Providers</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We may employ third party companies and individuals to facilitate our
              Service (<b>“Service Providers”</b>), provide Service on our behalf, perform
              Service-related services or assist us in analysing how our Service is used.
            </p>
            <p>&nbsp;</p>
            <p>
              These third parties have access to your Personal Data only to perform these
              tasks on our behalf and are obligated not to disclose or use it for any
              other purpose.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>12. Analytics</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We may use third-party Service Providers to monitor and analyze the use of
              our Service.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Google Analytics</b>
            </p>
            <p>&nbsp;</p>
            <p>
              Google Analytics is a web analytics service offered by Google that tracks
              and reports website traffic. Google uses the data collected to track and
              monitor the use of our Service. This data is shared with other Google
              services. Google may use the collected data to contextualise and personalise
              the ads of its own advertising network.
            </p>
            <p>&nbsp;</p>
            <p>
              For more information on the privacy practices of Google, please visit the
              Google Privacy Terms web page:{' '}
              <a href="https://policies.google.com/privacy?hl=en">here</a>
            </p>
            <p>&nbsp;</p>
            <p>
              We also encourage you to review the Google's policy for safeguarding your
              data: <a href="https://support.google.com/analytics/answer/6004245">here</a>
              .
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>13. CI/CD tools</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We may use third-party Service Providers to automate the development process
              of our Service.{' '}
            </p>
            <p>&nbsp;</p>
            <p>
              <b>GitHub</b>
            </p>
            <p>&nbsp;</p>
            <p>GitHub is provided by GitHub, Inc.</p>
            <p>&nbsp;</p>
            <p>
              GitHub is a development platform to host and review code, manage projects,
              and build software.
            </p>
            <p>&nbsp;</p>
            <p>
              For more information on what data GitHub collects for what purpose and how
              the protection of the data is ensured, please visit GitHub Privacy Policy
              page:{' '}
              <a href="https://help.github.com/en/articles/github-privacy-statement">
                here
              </a>
              .
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>14. Links to Other Sites</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              Our Service may contain links to other sites that are not operated by us. If
              you click a third party link, you will be directed to that third party's
              site. We strongly advise you to review the Privacy Policy of every site you
              visit.
            </p>
            <p>&nbsp;</p>
            <p>
              We have no control over and assume no responsibility for the content,
              privacy policies or practices of any third party sites or services.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>15. Children's Privacy</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              Our Services are not intended for use by children under the age of 13 (
              <b>“Children”</b>).
            </p>
            <p>&nbsp;</p>
            <p>
              We do not knowingly collect personally identifiable information from
              Children under 13. If you become aware that a Child has provided us with
              Personal Data, please contact us. If we become aware that we have collected
              Personal Data from Children without verification of parental consent, we
              take steps to remove that information from our servers.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>16. Changes to This Privacy Policy</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of
              any changes by posting the new Privacy Policy on this page.
            </p>
            <p>&nbsp;</p>
            <p>
              We will let you know via email and/or a prominent notice on our Service,
              prior to the change becoming effective and update “effective date” at the
              top of this Privacy Policy.
            </p>
            <p>&nbsp;</p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes.
              Changes to this Privacy Policy are effective when they are posted on this
              page.
            </p>
            <p>&nbsp;</p>
            <p>
              <b>
                <u>17. Contact Usy</u>
              </b>
            </p>
            <p>&nbsp;</p>
            <p>If you have any questions about this Privacy Policy, please contact us:</p>
            <p>&nbsp;</p>
            <p>By email: info@wefleet.co.</p>
          </FirstSection>
        </SubContainer>
      </MainContainer>
    </>
  )
}

const MainContainer = styled.div`
  margin: 10px 20px;
  padding: 0 3rem;
  @media screen and (min-width: 320px) and (max-width: 1080px) {
    padding: 0px;
  }
`

const SubContainer = styled.div`
  padding: 30px;
  @media screen and (min-width: 320px) and (max-width: 1080px) {
    width: 90%;
    padding: 0px;
  }
`

const FirstSection = styled.div`
  width: 100%;
  margin: 0px 30px;
`

const Title = styled.h2`
  font-weight: 700;
  text-align: center;
  margin-bottom: 50px;
`

export default PrivacyPolicy
